# Lang
language: en

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Archives: /archives
  Wiki: https://wiki.geekplux.com
  Presentation: /presentation
  Project: https://project.geekplux.com
  About: https://about.geekplux.com
  Donate: https://donate.geekplux.com
  关于: /about
  扯淡集: /gab
  RSS: /atom.xml
rss: /atom.xml

# Content
fancybox: true

# Miscellaneous
google_analytics: UA-46481966-2
favicon: /favicon.ico
twitter: GeekPlux
google_plus: # google plus
fb_admins: # fb admin
fb_app_id: # fb app
baidu_tongji: true

# Profile
nickname: GeekPlux
description: I am a web developer, open-source contributor, student and lifelong **learner** interested in everything.<br/> Now I focus on Data Visualization.

icons: false
links:
  Blog: /archives
  Wiki: https://wiki.geekplux.com
  GitHub: https://github.com/geekplux
  Instagram: https://www.instagram.com/geekplux
  Twitter: https://twitter.com/geekplux
  About: https://about.geekplux.com
  关于: /about

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content: I'm **[GeekPlux](/about)**, a web developer who contributes to open-source projects. You are reading my [blog](http://geekplux.com) powered by [Hexo](https://hexo.io) and [Typing](https://github.com/geekplux/hexo-theme-typing). All articles are under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). Follow me on [Twitter](https://twitter.com/geekplux) for communicating, [GitHub](https://github.com/geekplux) for code, and [Instagram](https://www.instagram.com/geekplux) for daily.
post_footer_content: I'm **[GeekPlux](/about)**, a web developer who contributes to open-source projects. You are reading my [blog](http://geekplux.com) powered by [Hexo](https://hexo.io) and [Typing](https://github.com/geekplux/hexo-theme-typing). All articles are under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). Follow me on [Twitter](https://twitter.com/geekplux) for communicating, [GitHub](https://github.com/geekplux) for code, and [Instagram](https://www.instagram.com/geekplux) for daily.

# Gitment
gitment:
  owner: # owner
  repo: # repo
  client:
    id: # id
    secret: # secret

# Utterances
# NOTICE) make sure the app is installed on the repo before using this commit system
# see https://utteranc.es/ for more
utterances:
  enable: false
  repo: # your repo in this format: 'username/reponame', note that there is no '.git' suffix

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId: # your leancloud appId
  appKey: # your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn

# Donate
donate:
  github: https://github.com/geekplux
  paypal: https://www.paypal.me/geekplux
  bitcoin: 1AVngxh56oLvAzXsEFnzccUohZdHswjC7j
  BTCQR: https://geekpluxblog.oss-cn-hongkong.aliyuncs.com/donate/bitcoin.png
  AliPayQR: https://geekpluxblog.oss-cn-hongkong.aliyuncs.com/donate/alipayQR.jpg
  WeChatQR: https://geekpluxblog.oss-cn-hongkong.aliyuncs.com/donate/wechatQR.jpg
